### ISSUE TITLE
Performance mode breaks effects

### ISSUE THREAD

**Issue by gabriele2000** [martymcmodding/iMMERSE#1]
Basically if I enable "performance mode" on ReShade, effects such as RTGI and MXAO doesn't work well, it's like a different depth buffer is issued to the shaders, breaking them.

Disabling it fixes every issue.

**Comment by martymcmodding** [comment]
I'll look into it. Normally I'd thank you for the bug report but as you're frequenting drownedmods and pirated my work, you can kindly fuck off.

**Comment by gabriele2000** [comment]
> I'll look into it. Normally I'd thank you for the bug report but as you're frequenting drownedmods and pirated my work, you can kindly fuck off.

Oh, I would like to buy your work, but €5 a month is still a subscription to something that's still being developed since YEARS...
By the way, how's the money working out for ya? Doin' well with those minimum €3000 a month thanks to patreon?

**Comment by TreyM** [comment]
"I know! I'll report a bug on something I'm a known pirate for, then I'll act like a victim when the dev I stole from tells me to fuck off!"

**Comment by gabriele2000** [comment]
> "I know! I'll report a bug on something I'm a known pirate for, then I'll act like a victim when the dev I stole from tells me to fuck off!"

Oh no, you're spamming even here... anyway
