### ISSUE TITLE
Reshade not successfully loading .fx files from immerse

### ISSUE THREAD

**Issue by Serre3264** [martymcmodding/iMMERSE#12]
[ReShade.log](https://github.com/martymcmodding/iMMERSE/files/14546454/ReShade.log)

Dear Marty,

I used reshade on Skyrim SE and it seems to have some issue when loading immerse files.reshade says that "...warning X3554:solaris.fx has unknown attribute branch or attribute invalid for this statement", can I fix this?

My log is attached for review.

**Comment by martymcmodding** [comment]
Support for Pro and Ultimate shaders only on my Discord and only for legit customers.

**Comment by Serre3264** [comment]
I am a Pateron supporter and my identity is jeuneserre on Pateron. Why would you identify me as illegal users?
________________________________
发件人: martymcmodding ***@***.***>
发送时间: 2024年3月13日 20:04
收件人: martymcmodding/iMMERSE ***@***.***>
抄送: Serre3264 ***@***.***>; Author ***@***.***>
主题: Re: [martymcmodding/iMMERSE] Reshade not successfully loading .fx files from immerse (Issue #12)


Support for Pro and Ultimate shaders only on my Discord and only for legit customers.

―

**Comment by martymcmodding** [comment]
I didn't identify you as an illegal user, I just said if you're a legit customer, please seek support on my Discord, this is not the right place.
