### ISSUE TITLE
ReShade 6.3.3 MartysMods_SMAA.fx failed to compile

### ISSUE THREAD

**Issue by KiwiMonkeyUSA** [martymcmodding/iMMERSE#18]
Brand new install of ReShade 6.3.3, usually do a full download of shaders. Launched a game and had this error pop up:

Error: V__DepthTex: another effect (SSAO.fx) already created a texture with the same name but different semantic

**Comment by martymcmodding** [comment]
That's not an error, that's a warning. If 2 shaders declare textures with identical names and different properties, one shader wins and the other has to deal with a different texture. 

I don't know from which source you got SSAO.fx but it's ancient and I highly advise to use iMMERSE MXAO instead, if you want any AO.
