### ISSUE TITLE
"mv" used without being initialized

### ISSUE THREAD

**Issue by WoodyPWX** [martymcmodding/iMMERSE#3]
Hey,
it could be handled by shader compiler, but in the MXAO shader, func. "filter", the first "mv +=", at line 615, should be "mv =" instead.
It hasn't been initialized yet. The #pragma warning(disable : 4000), used there, is suppressing any warning about that.
Regards,
Tomas

**Comment by martymcmodding** [comment]
Good point, I'll fix it.

**Comment by martymcmodding** [comment]
Forgot about this, fixed on dev
