### ISSUE TITLE
About iMMERSE sharpen

### ISSUE THREAD

**Issue by sanek7814** [martymcmodding/iMMERSE#4]
Can you change the code of this sharpening filter to darken pixels more than lighten them? Why am I writing this, as I understand your shader is similar to amd's CAS shader. Both of these shaders are designed to remove blurriness caused by TAA anti-aliasing.  And both of these shaders I tested in half life 2 result is the same. But in the game Witcher 3 I used rj200 shader instead of cas which gave better results as I understood from darkens pixels.  Can you do the same? Just for the sake of experimenting, maybe it will give more realistic results.

**Comment by martymcmodding** [comment]
Hm, that's kind of not how it works. See, a sharpen filter does the following:

1) create a blurred copy of the original image
2) observe how the colors change from sharpened to blurry image and move colors in the sharp image to the "opposite" direction

Of course, things are a bit more involved to minimize halos, detect how much you can move without exiting the space of displayable colors and what not.

But it's not usually the case you'd adjust this behavior on its own. Sure, some sharpen filters perform their operation in linear space, some in gamma space, so they tend to behave differently. 

I tried to adhere to the paradigm that ideally, the sharpened image should not have a perceptible change in brightness overall and doing this would break that.
