### ISSUE TITLE
Do not buy rtgi 0.36.1. Ghosting everywhere. E.g. GBTVG Rem.

### ISSUE THREAD

**Issue by Jimmysikisken** [martymcmodding/iMMERSE#7]
Ghosting everywhere. Do not buy the Marty/Pascal Gilcher 0.36.1 version. DO not spend your money. The new version breaks games (ghosting). Use another lighting solution.

**Comment by jjayrex** [comment]
I do not know how you would buy an older version, however the most recent version is 0.41 and it is advised to always use the latests. Version 0.40 was a major redesign, thus older versions might not function correctly with other iMMERSE effects.

Perhaps you are downloading directly from Patreon, whereas the new versions are uploaded to Discord.
